module.exports = {
	BotError : require("./BotError"),
	Undefined : require("./Undefined"),
	Type : require("./Type"),
	InvalidData : require("./InvalidData"),
	Find : require("./Find"),
	Range : require("./Range"),
	Unexisting : require("./Unexisting"),
	Dublication : require("./Dublication"),
	Command : require("./Command"),
	CommandNameNotFound : require("./CommandNameNotFound"),
	ParameterArguments : require("./ParameterArguments"),
	ParameterDependency : require("./ParameterDependency"),
	ParameterRequired : require("./ParameterRequired"),
};
